[project]
name = "rating-evaluation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiokafka>=0.13.0",
    "autogluon>=1.5.0",
    "confluent-kafka>=2.13.0",
    "flaml>=2.5.0",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "kafka-python>=2.3.0",
    "langchain>=1.2.6",
    "langchain-ollama>=1.0.1",
    "psycopg2-binary>=2.9.11",
    "pygraphviz>=1.14",
    "fastapi>=0.129.2",,
    "joblib>=1.5.3",
    "mlflow>=3.10.0",
    "pandas>=2.3.3",
    "scikit-learn>=1.8.0",
    "uvicorn>=0.41.0",
]
